version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: influenceMobileGame_development
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.2.1"
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app:cached
    depends_on:
      - db
    environment:
      TZ: 'America/Toronto'
      DATABASE_URL: postgres://user:password@db:5432/influenceMobileGame_development

volumes:
  pgdata:
