services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: influenceMobileGame_development
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: "3.2.1"
    volumes:
      - .:/app:cached
    depends_on:
      - db
    environment:
      TZ: 'America/Toronto'
      DATABASE_URL: postgres://user:password@db:5432/influenceMobileGame_development
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

volumes:
  pgdata:
